language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install pygame

# command to run tests
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - cd ./client/core
script: python main.py


